name=RMUTP_CARBOT
version=1.0.0
author=Supong Chalermchainuwong <supongkill555@gmail.com>
maintainer=Supong Chalermchainuwong <supongkill555@gmail.com>
sentence=ESP32 motor driver library for car robot (L298N).
paragraph=Control DC motors with PWM, direction, and turning functions. Designed for ESP32 only.
category=Device Control
url=https://github.com/yourname/RMUTP_CARBOT
architectures=esp32